// PotholeReport.kt
package com.potholereporter.ai.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a single Pothole Report entity for the Room database.
 */
@Entity(tableName = "pothole_reports")
data class PotholeReport(
    // Auto-generated primary key for the database
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // File path where the photo is saved on internal storage
    val imagePath: String,

    // GPS location data
    val latitude: Double,
    val longitude: Double,

    // The severity score generated by the AI model
    val severityScore: Float,

    // Timestamp when the report was created (in milliseconds)
    val timestamp: Long
)